name: C++ Build and Test

on: #When to run this code
  push:
    branches:
      - main #When someone pushes this to main branch
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest #Where will it run

    steps:
    - name: Checkout code #Download our code to somewhere
      uses: actions/checkout@v4

    - name: Set up C++ environment
      run: sudo apt-get install g++ #To compile C++ we need g++

    - name: Compile the code
      run: |                                        #auto run it
        g++ -o fibonacci fibonacci.cpp 

    - name: Run the application                 #Run and check
      run: |
        echo "Running on Ubuntu"
        ./fibonacci  12 # For Ubuntu

    - name: Upload artifacts            #testing phase - running in ubuntu latest
      uses: actions/upload-artifact@v4
      with:
        name: fibonacci-output
        path: |
          fibonacci
#The same programing code is made on run on mulltiple os
  build-windows:                       #For windows running 
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ environment
      run: |  
        choco install mingw  # Assumes you have Chocolatey installed on Windows

    - name: Compile the code
      run: |
          g++ -m64 -o fibonacci_windows.exe fibonacci.cpp


    - name: Run the application
      run: |
        echo "Running on Windows"
        .\fibonacci_windows.exe  10 # For Windows

    - name: Upload artifacts      #uploads resultant file 
      uses: actions/upload-artifact@v4
      with:
        name: fibonacci-output-windows
        path: |
          fibonacci_windows.exe
